### ISSUE TITLE
Default to add label if MODS or DC being ingested

### ISSUE THREAD

**Issue by nate-rcl** [SFULibrary/islandora_datastream_crud#18]
Would it make more sense to default to add new labels to objects when ingesting MODS or DC?  It would seem to be the more likely case that object titles should be updated rather than not updated when ingesting new MODS or DC metadata.

**Comment by mjordan** [comment]
@nate-rcl yes, that makes sense.

**Comment by mjordan** [comment]
@nate-rcl https://github.com/mjordan/islandora_datastream_crud/pull/11 should do this already.

**Comment by nate-rcl** [comment]
@mjordan correct - it does -  however you have to explicitly set the flag - I'm suggesting that there should be a Y/N option with the default to Y or have a flag to explicitly not updating the label rather than a flag for updating the label.  Currently if you forget to set the flag - which I did - you can import quite a few files without knowing that the labels will not be updated - even if they are different - which would seem to be an unexpected problem.  I am suggesting the default expectation when updating MODS/DC with a different label would be to update the object label versus not update the label.

**Comment by mjordan** [comment]
@nate-rcl I'm not sure if you've seen the discussion going on at #34, but I've added an option to generate object labels from a specific datastream using an entirely new command (`islandora_datastream_crud_update_object_properties`). Your use case is to not have to remember to set the `--update_object_label` flag, but with the ability to run a separate command to achieve the same ends where you presumably already have a PID file listing all the objects you'd be updating, I'm wondering if we can close this issue?

**Comment by nate-rcl** [comment]
@mjordan I did take a quick look - I'm not sure I quite understand - why would need to run two commands now to do the same thing that one command did? I would just expect it to grab the titles from the default source and stick them in the other metadata source. 

Also for multiple titles - why would you separate them by a "/". All mods and dc fields are repeatable. I would expect them to go int multiple title fields. When using the display I would expect this is where all the titles would be concatenated together with a "/" if that is what is wanted. Just my quick thoughts. 

If you feel the other way is better (#34) feel free to close this - I'll have to test it once you have it all set. I don't think the concatenation of the titles will work for us if you are collapsing them into a single xml element with a "/" as we store them as repeated title elements and concatenate them on the front end when necessary with a comma.

**Comment by mjordan** [comment]
@nate-rcl thanks for the feedback.

> why would need to run two commands now to do the same thing that one command did? I would just expect it to grab the titles from the default source and stick them in the other metadata source.

Totally valid question. Couple answers:

1. To be able to address more use cases. All three of the use cases provided in #34 use MODS, not DC, and SFU has a repo that doesn't even use MODS, it uses DDI as its canonical metadata datastream. Right now, the implementation in the issue-34 branch only allows specifying either MODS or DC as the source DSID, but I'm going to expand that to allow any source DSID (still trying to figure out how to auto-register arbitrary namespaces with PHP's XPath processor).
1. Related to the first point, I'd like to deprecate the `--update_object_label` option accompanying `islandora_datastream_crud_push_datastreams` as it is currently implemented since it only allows DC datastreams as the source of the label. Deprecating this would also allow me to reduce the complexity of the code that executes `islandora_datastream_crud_push_datastreams`. The more options used by a drush command, the more `if {}` statements end up in the code (at least [in the code that I write](https://github.com/mjordan/islandora_datastream_crud/blob/7.x/includes/utilities.inc#L163)).

> Also for multiple titles - why would you separate them by a "/". All mods and dc fields are repeatable. I would expect them to go int multiple title fields. 

Agreed, my choice of "/" is totally arbitrary, and there really should be an additional option to allow the user to decide what string to use to concatenate repeated titles. I'll add a comment to #34 to say this should be an option.

But on your other point, dc:title (and mods:titleInfo/mods:title) are repeatable whereas an object's label is not. If we're going to populate the label from potentially repeatable XML elements, we need a way to reduce multiple strings into one string. Two approaches to dealing with this (there may be others) are:

1. Providing a way of concatenating them in the resulting object label; the benefit of this approach is that it lets users assemble MODS `<titleInfo>` subelements like `<nonSort>` and `<title>` if they can come up with sophisticated enough XPath expression.
1. Using XPath that only ever selects a single source element to populate the object label. For example, if you wanted to only select the first occurrence of an element and not worry about dealing with repeated values, you could use a `--source_xpath` expression like "//mods:titleInfo[1]/mods:title[1]".

> store them as repeated title elements and concatenate them on the front end when necessary with a comma.

Are you manipulating the object label on the front end or are you manipulating DC/MODS values? I assume DC/MODS values since the label is not repeatable (but I could be completely wrong about that). If you're manipulating DC/MODS values, you could still do that, since this new feature (`islandora_datastream_crud_update_object_properties --update_object_label`) only populates the object label, it doesn't touch the datastream content. Let me know if I'm not understanding what you're doing here. I'd like to know more.

**Comment by nate-rcl** [comment]
@mjordan sounds good and thanks for the explanation - we manipulate on the search and front end. I think I understand what you mean now - the label is separate from the titles - which is kind of weird. Not sure why this is. We do separate our titles with a comma.

We display all of our metadata from the solr metadata index. Here is an example of a record with 2 titles (you'll have to scroll down to see it in the metadata):

https://digitalcollections.lib.rochester.edu/ur/nebraska-seedling-plum

It is stored in two different mods title fields. The search works and shows both titles:

https://digitalcollections.lib.rochester.edu/islandora/search/Nebraska%20Seedling%20Plum?type=dismax

Unfortunately both titles do not show up at the top of the page yet - which must be the label.

**Comment by mjordan** [comment]
The label being separate from the title is weird, but I think it's correct to say that the label is an object property (it's actually represented in Islandora code as `$object->label`) that is required by Fedora, whereas the "title" we think of is just a value from a datastream like MODS. To make matters even more confusing, the two get conflated in the dc:title element, since that is where Fedora copies the object label by default. And... the label is what is used by default in collection browse lists and search results, not a value taken directly from MODS or DC. It's all very confusing.

**Comment by mjordan** [comment]
@nate-rcl thanks for the use cases and comments. I'll close this issue and link from there to #34 for future reference
