### ISSUE TITLE
PIDs with _ in them result in are not round tripable

### ISSUE THREAD

**Issue by mjordan** [SFULibrary/islandora_datastream_crud#33]
It is valid for a PID to contain an underscore after the `:`. In PIDs that contain an underscore after the `:`, the function that converts datastream fileanames back into PIDs (`islandora_datastream_crud_dsfilename_to_pid`) returns the wrong PID. For example,  the PID `crud:foo_5` will result in the MODS ds filesname `crud_foo_5_MODS.xml`, and will be converted back into the PID `crud:5`.

Since having underscores in the post-colon part of a PID is likely uncommon, I will document this as a known issue until it is fixed.

**Comment by wgilling** [comment]
Since we have a lot of objects with custom PID values, I wanted to test the version of the code that was fixed for #30 - I suspected that the change to the code would not address the underscore issue, but I figured that I could test it.

The PID values that I exported MODS for were:
pitt:MSP301_B003_F002_I16
pitt:200907.____.01260
pitt:PSS_028_B001_F006_I017

These were saved in files named:
pitt_MSP301_B003_F002_I16_MODS.xml
pitt_200907.____.01260_MODS.xml
pitt_PSS_028_B001_F006_I017_MODS.xml

These all exported successfully but the import function failed with the message:
The specified object (pitt:200907.) does not exist or is not accessible. [error]
The specified object (pitt:MSP301) does not exist or is not accessible. [error]
The specified object (pitt:PSS) does not exist or is not accessible.   [error]

I hope this info helps in some way.   😞

**Comment by mjordan** [comment]
@bgilling thanks, it does, since it confirms the bug and also confirms a real use of `_` in PIDs. My approach to solving this issue so far is to allow the user (that would be you in this case!) to supply a string via a drush option (`--filename_separator` or something) to use to use as a seprator between the two halves of the PID (one before the `:` and one after) and before the DSID in the filename used in the datastream file. The default would be as it is now (`_`) but any string provided as this option would need to be filesystem safe for your operating system and would need to provide round-trippable conversion from PID to datastream filename back to PID plus DSID.

Allowing the user to provide the string to use assumes that the user knows which characters do not occur in their PIDs, which is probably a safe assumption. Also, Islandora Datastream CRUD could advise the user if it finds an `_` in a PID,

**Comment by wgilling** [comment]
This seems like the absolute way to control this... especially considering that datastreams can also contain the underscore character (doesn't RELS-EXT get renamed to RELS_EXT in the system).

I assume that the code for import and export functions would assume a working default value for this filename_separator variable as an underscore.

This change would certainly require an addition to the README.

Please let me know if there is anything that I can do to assist.

**Comment by mjordan** [comment]
> This seems like the absolute way to control this... especially considering that datastreams can also contain the underscore character (doesn't RELS-EXT get renamed to RELS_EXT in the system).

I'll make sure to check that.

> I assume that the code for import and export functions would assume a working default value for this filename_separator variable as an underscore.

Yes.

> This change would certainly require an addition to the README.

Agreed

> Please let me know if there is anything that I can do to assist.

Will do thanks! I'll likely ask you to test when I have something.

**Comment by mjordan** [comment]
Just noting an idea here. Maybe we can avoid cumbersome replacements by using the raw PID in filenames and URL encoding them before writing the files. (See [this blog post](https://evertpot.com/filesystem-encoding-and-php/) for more info.) Then, when we read the filenames, we can get the original PID back by URL decoding them.

**Comment by mjordan** [comment]
@bgilling I have done some work on this 1.5 year old issue. If you are still interested, I'd appreciate it if you could test my fix. In a nutshell, if you add the `--filename_separator` option with a character like `^` or `#` when you fetch or push datastreams, you can use `_` anywhere you like in the DSID or PID. The section in the issue-67 branch's README with the heading "Dealing with underscores in PIDs or datastream IDs" had more detail.

**Comment by wgilling** [comment]
@mjordan I would be happy to test this out this week - I expect that I will have sufficient time tomorrow (2019/02/20) to use that option.

Soon after this, I can add a configuration for this option for the islandora_datastreams_io interface.

**Comment by wgilling** [comment]
One tiny issue that I ran into when I tried this on the command line was caused that I used an illegal character.  I chose to try  `--filename_separator=|` which has the unfortunate result of causing the executed command to split on the pipe character.

Here are the results when I called the export with different separator values:

filename_separator | exported filename
------------ | -------------
(no setting) | pitt_20091209-kogyo-0283_DC.xml
"_" | pitt_20091209-kogyo-0283_DC.xml
"[]" | pitt:20091209-kogyo-0283[]DC.xml
"-" | pitt:20091209-kogyo-0283-DC.xml
"._" | pitt:20091209-kogyo-0283._DC.xml

My commands were all very similar to this:

> drush islandora_datastream_crud_fetch_datastreams -u 1 --pid_file=/tmp/pids_file.txtaXqQs4 --dsid=DC --datastreams_directory=/tmp/datastream_io_datastreams_161849_040249 --filename_separator=._ -y --uri=http://infost01-02.library.pitt.edu:8000


The only thing that puzzles me is that the ":" after the object namespace is only changed to an underscore when the filename_separator is either set to "_" or is not supplied (default).  Is this intentional?

**Comment by mjordan** [comment]
@bgilling thanks for the thorough test. I'm not surprised `|` caused havoc since it has a specific use in most shells, but apparently if you really want to use it, `\|` will do the trick. I wonder if it would be OK to prohibit the use of `|` - do you think anyone would miss it?

That's right, I kept the `:` in an effort to keep the PIDs intact to the extent possible. Substituting `:` for `_` was, in retrospect, a bad idea (and here we are today.....). The reason I left the default behavior intact is to not break any scripts that people might be using to write out datastream files outside of Islandora. I am not sure if anyone is doing that (other than us, in one of our migrations), but I thought leaving the default behavior intact while also leaving the PID intact if the user supplied a value other than `_` was the right thing to do.

**Comment by wgilling** [comment]
I think it is good to have this parameter option now... and I don't think that the pipe character would be something that people need to use particularly.  As developers, we certainly are familiar with some characters that would cause problems -- and we know what we're doing when we use that option to set a delimiting character --- for example, I suppose that we all know that we'd be in trouble if we decided to pick a "0" as the separating character.

I suppose that there are a set of logical delimiters -- and the only ones that should truly be illegal to set would be any that cause illegal filenames.  For example, selecting the "*" character or "/" would have obvious filenaming problems.  Should your code be responsible for validating that character selection?  Dunno.

Understandable about the colon and others using the code.  I can say that the current version of my islandora_datastreams_io module still works with the latest code.

Is there anything else that I can do?

**Comment by mjordan** [comment]
@bgilling thanks very much for testing. I think I will add '*' and '/' to the prohibited character list, since I can't think of a valid (or even workable) use case for them and not all users will think of the implications of using them. And thanks for testing how this change will impact islandora_datastreams_io.

**Comment by wgilling** [comment]
you're very welcome -- and thank you for all that you do.

**Comment by mjordan** [comment]
Merged with 60ed72125023fd27adf8bb8f2df94f20d1cce84b.
