### ISSUE TITLE
More Solr query examples

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#56]
It is quite difficult to comprehend how a complex Solr query should be formulated. For example, I want to use the following:

`PID:capu\:*&fq=-RELS_EXT_hasModel_uri_s:islandora\:collectionCModel&fq=-mods_genre_s:reports&fq=-mods_genre_s:clippings*&fq=-mods_genre_s:letters*`

which is valid if you put it in Solr, but not valid for this module. How would a Solr query with more than one field or with filters be used here?

**Comment by mjordan** [comment]
There are a lot of shell characters in that query. What happens if you wrap the entire query in double quotes?

**Comment by bondjimbond** [comment]
It was all in double quotes when I attempted it. I tried several iterations, but nothing worked; can't figure out the correct way to do it.

**Comment by mjordan** [comment]
Can you try building up the parameters at a time until it works, in order to narrow down what character is making it not work? For example, 

```
PID:capu\:*
```
then
```
PID:capu\:*&fq=-RELS_EXT_hasModel_uri_s:islandora\:collectionCModel
```
then 
```
PID:capu\:*&fq=-RELS_EXT_hasModel_uri_s:islandora\:collectionCModel&fq=-mods_genre_s:reports
```
etc.

If it works in the Solr web UI but not on the command line, I strongly suspect that it isn't being passed into Drush properly because of a shell metacharacter cutting the query string off.

Another approach is to add `var_dump($query)` at line 322 in islandora_datastream_crud.drush.inc and observe what gets dumped to see if it is in fact being truncated.

**Comment by bondjimbond** [comment]
OK, I think I'm getting the idea. Here's a query that worked in Vagrant:

`drush islandora_datastream_crud_fetch_pids --solr_query="RELS_EXT_isMemberOfCollection_uri_ms:info\:fedora\/ir\:citationCollection AND dc.title:citation AND -mods_genre_s:letters" --pid_file=/var/www/drupal/sites/solr1.txt`

A space between the ANDs is important, and instead of "fq" just put a "-".

Can we document that in the readme? Maybe just use the above as an example complex query?

**Comment by mjordan** [comment]
Nice work. I can start a new section called "Solr queries" and put between the "Fetching PIDs" and "General workflow" sections with this example if you want. Or if you want to open a PR that would be cool.

**Comment by mjordan** [comment]
@bondjimbond thanks for the excellent example. Close this if you want.
